#!/usr/bin/env python3
"""
spacex_tv_reconcile.py — Compare expected TradingView state with actual.
GO_SPACEX_TV_AUTOMATION_MAX_01

Reads: configs/tradingview/spacex_tv_targets.yaml
Actions: tv-snapshot → compare → report drift → generate missing jobs
Mutations: only with --gate-approved
"""
from __future__ import annotations
import argparse, json, subprocess, sys, os
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parents[2]
SUPPORTED_ALERT_FREQUENCIES = {"on_bar_close", "on_first_fire"}
FREQUENCY_ALIASES = {
    "once_per_bar": "on_bar_close",
    "every_bar_close": "on_bar_close",
}

def load_targets() -> dict:
    import yaml
    path = REPO_ROOT / "configs" / "tradingview" / "spacex_tv_targets.yaml"
    return yaml.safe_load(path.read_text())

def run_tv_snapshot(dry_run: bool = True) -> dict:
    """Run TradingView snapshot via orchestrator."""
    cmd = [
        sys.executable, "-m", "modules.tradingview_orchestrator.app.tv_runner",
        str(REPO_ROOT / "modules" / "tradingview_orchestrator" / "jobs" / "examples" / "tv_job_snapshot.json"),
    ]
    if dry_run:
        print("[DRY-RUN] Would run: tv-snapshot")
        return {"alerts": [], "indicators": [], "symbol": "SPCX", "timeframe": "1"}
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"error": result.stderr[:200]}

def reconcile(targets: dict, actual: dict) -> dict:
    """Compare targets vs actual TV state."""
    report = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "expected_alerts": len(targets.get("required_alerts", [])),
        "actual_alerts": len(actual.get("alerts", [])),
        "missing_alerts": [],
        "drift_status": "UNKNOWN",
        "jobs_generated": [],
    }

    expected_ids = {a["id"] for a in targets.get("required_alerts", [])}
    actual_ids = {a.get("id", a.get("alert_id", "")) for a in actual.get("alerts", [])}
    report["missing_alerts"] = sorted(expected_ids - actual_ids)
    report["extra_alerts"] = sorted(actual_ids - expected_ids)

    if not report["missing_alerts"] and not report.get("extra_alerts"):
        report["drift_status"] = "CLEAN"
    else:
        report["drift_status"] = "DRIFT"

    return report

def normalize_frequency(value: str | None) -> str:
    frequency = (value or "on_bar_close").strip()
    frequency = FREQUENCY_ALIASES.get(frequency, frequency)
    if frequency not in SUPPORTED_ALERT_FREQUENCIES:
        allowed = ", ".join(sorted(SUPPORTED_ALERT_FREQUENCIES))
        raise ValueError(f"unsupported TradingView frequency '{frequency}' (allowed: {allowed})")
    return frequency

def build_webhook_message(targets: dict, alert_id: str) -> dict:
    """Flatten the YAML webhook payload template into the alert message body."""
    payload_template = targets.get("webhook_payload", {})
    message = {
        k: v for k, v in payload_template.items()
        if k != "fields" and not isinstance(v, (dict, list))
    }
    for item in payload_template.get("fields", []):
        if isinstance(item, dict):
            message.update(item)
    message.setdefault("event", alert_id)
    message.setdefault("alert_name", alert_id)
    message.setdefault("signal", alert_id)
    return message

def generate_missing_jobs(targets: dict, report: dict) -> list[dict]:
    """Generate tv_job_v1 alert.create jobs for missing alerts."""
    jobs = []
    webhook_url = targets.get("webhook_url", "")

    for alert in targets.get("required_alerts", []):
        if alert["id"] in report.get("missing_alerts", []):
            job = {
                "schema": "tv_job_v1",
                "id": f"tv_job_alert_create_spcx_{alert['id'].lower()}",
                "type": "alert.create",
                "params": {
                    "symbol": targets.get("symbol_tv", "BATS:SPCX"),
                    "condition": alert.get("condition", "crossing"),
                    "price": alert.get("price", 1),
                    "frequency": normalize_frequency(alert.get("frequency")),
                    "name": alert["id"],
                    "webhook_url": webhook_url,
                    "message": build_webhook_message(targets, alert["id"]),
                },
                "gate": "approved",
                "created_at": datetime.now(timezone.utc).isoformat(),
                "status": "pending",
                "notes": f"Auto-generated by spacex_tv_reconcile.py — missing alert {alert['id']}",
            }
            jobs.append(job)
            report["jobs_generated"].append(job["id"])

    return jobs

def main():
    p = argparse.ArgumentParser(prog="spacex_tv_reconcile")
    p.add_argument("--dry-run", action="store_true", default=True, help="Read-only, no mutations")
    p.add_argument("--apply", action="store_true", help="Apply missing job creation")
    p.add_argument("--gate-approved", action="store_true", help="Required for mutation")
    args = p.parse_args()

    targets = load_targets()
    print(f"Target: {targets['symbol']} ({targets['symbol_tv']})")
    print(f"Webhook: {targets['webhook_url']}")
    print(f"Required alerts: {len(targets['required_alerts'])}")
    print()

    actual = run_tv_snapshot(dry_run=args.dry_run)
    report = reconcile(targets, actual)

    print(f"Drift status: {report['drift_status']}")
    print(f"Expected alerts: {report['expected_alerts']}")
    print(f"Actual alerts: {report['actual_alerts']}")
    print(f"Missing: {len(report['missing_alerts'])} {report['missing_alerts'][:5]}")
    print(f"Extra: {len(report.get('extra_alerts',[]))} {report.get('extra_alerts',[])[:5]}")
    print()

    if report["drift_status"] == "DRIFT":
        jobs = generate_missing_jobs(targets, report)
        print(f"Generated {len(jobs)} missing alert jobs:")
        for j in jobs:
            print(f"  {j['id']}")

        if args.apply and args.gate_approved:
            out_dir = REPO_ROOT / "modules" / "tradingview_orchestrator" / "jobs" / "spacex" / "generated"
            out_dir.mkdir(parents=True, exist_ok=True)
            for j in jobs:
                out_path = out_dir / f"{j['id']}.json"
                out_path.write_text(json.dumps(j, indent=2))
                print(f"  WRITTEN: {out_path}")
        else:
            print("  (dry-run — use --apply --gate-approved to write jobs)")

    # Write drift report
    report_dir = REPO_ROOT / "reports" / "tradingview"
    report_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    report_path = report_dir / f"spacex_tv_drift_{ts}.json"
    report_path.write_text(json.dumps(report, indent=2, default=str))
    print(f"\nReport: {report_path}")

if __name__ == "__main__":
    main()
