<# Autogenerated: Delete A_SUPPRIMER branches both locally and remotely, log results #>
$ErrorActionPreference = 'Stop'
$logPath = 'docs/chantiers/GO_OPT_TRADING_BRANCH_ARBITRATION_DELETE_AND_BRANCH_STATE_03/delete_results.txt'
Set-Content -Path $logPath -Value "Delete plan started: $(Get-Date -Format o)" -Encoding UTF8

$branches = @(
  'audit/opt-trading-20260320a',
  'docs/github-park-parent-closeout-01',
  'docs/github-park-pass-close-01',
  'feat/journal-api-extractor-bootstrap',
  'feat/journal-api-extractor-v1',
  'feat/mimo-open-observer-doc-pack-v0',
  'feat/student-mimo-qualification',
  'METHODE_MULTI_MACHINE_GIT_SYNC',
  'wip/GO_GITHUB_PARK_AUDIT_EXPANSION_ISOLATE_01'
)

foreach ($b in $branches) {
  Add-Content -Path $logPath -Value "Processing $b" -Encoding UTF8
  git show-ref --verify --quiet "refs/heads/$b" 2>&1
  if ($LASTEXITCODE -eq 0) {
    Add-Content -Path $logPath -Value "Deleting local $b" -Encoding UTF8
    $localOut = git branch -D "$b" 2>&1
    Add-Content -Path $logPath -Value $localOut -Encoding UTF8
  } else {
    Add-Content -Path $logPath -Value "Local $b not found" -Encoding UTF8
  }

  $remoteOut = git ls-remote --heads origin "$b" 2>&1
  if ($remoteOut -and $remoteOut -match 'refs/heads/') {
    Add-Content -Path $logPath -Value "Deleting remote $b" -Encoding UTF8
    $remoteDel = git push origin --delete "$b" 2>&1
    Add-Content -Path $logPath -Value $remoteDel -Encoding UTF8
  } else {
    Add-Content -Path $logPath -Value "Remote $b not found" -Encoding UTF8
  }
}

Add-Content -Path $logPath -Value "DONE" -Encoding UTF8
