#!/usr/bin/env python3
"""Status summary — JSON de santé pour le CI/scheduler/monitoring.

Usage:
  python3 scripts/ai/workers/health_status.py [--output reports/ai/health_status.json]
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]


def git_info():
    try:
        branch = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, cwd=REPO_ROOT
        ).stdout.strip()
        commit = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=REPO_ROOT
        ).stdout.strip()
        return {"branch": branch, "commit": commit}
    except Exception:
        return {"branch": "unknown", "commit": "unknown"}


def kill_switch_state():
    ks_path = REPO_ROOT / "data/runtime_health" / "kill_switch.state"
    if ks_path.exists():
        return ks_path.read_text().strip()
    return "NORMAL"


def count_ledger_events():
    ledger_path = REPO_ROOT / "data/runtime_health" / "ledger" / "events.jsonl"
    if not ledger_path.exists():
        return 0
    try:
        with open(ledger_path) as f:
            return sum(1 for _ in f)
    except Exception:
        return -1


def check_systemd_timers():
    """List known systemd timer states (best-effort)."""
    timers = ["opt-trading-runtime-health.timer", "opt-trading-fleet-orchestrator.timer"]
    states = {}
    for t in timers:
        try:
            r = subprocess.run(
                ["systemctl", "is-active", t],
                capture_output=True, text=True, timeout=5
            )
            states[t] = r.stdout.strip()
        except Exception:
            states[t] = "unknown"
    return states


def build_status():
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git": git_info(),
        "kill_switch": kill_switch_state(),
        "ledger_event_count": count_ledger_events(),
        "systemd_timers": check_systemd_timers(),
        "health": {
            "status": "OK",
            "note": "Status generated by health_status.py"
        }
    }


def main():
    parser = argparse.ArgumentParser(description="Health status JSON generator")
    parser.add_argument("--output", default=None, help="Write output to file")
    args = parser.parse_args()

    status = build_status()
    output = json.dumps(status, indent=2)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output + "\n")
        print(f"Status written to {output_path}")
    else:
        print(output)


if __name__ == "__main__":
    main()
